FM1 =t,fm0,a
FM2 =t,fm1,b
FM3 =t,fm2,c
FM4 =
FM5 =
FM6 =
FMR =
FM7 =t,fm3,a
FM8 =t,fm4,b
FM9 =t,fm5,c
PSG1=t,ps0,a
PSG2=t,ps0,b
PSG3=t,ps0,c
SCC1=t,sc0,a
SCC2=t,sc0,b
SCC3=t,sc0,c
SCC4=t,sc3,a
SCC5=t,sc3,b

t=t130

fm0=v12@12o5
fm1=v12@14o5
fm2=v12@16o5
fm3=v10@12o5 r16 z30
fm4=v10@14o5 r16 z30
fm5=v10@16o5 r16 z30
ps0=o4v9 @4
sc0=o4v7 @3
sc3=o4v5 @3 r16 z12


a=l16>b>dgbg4 r1
b=l16dgb>d<b4r1
c=g8.>d16<g4 r1

